name: RooziesPlugin
version: 0.1-1.21.5
main: com.roozie.roozieplugin.RooziesPlugin
description: A custom plugin for roleplay
author: Djskinproductions, FutureVoyager
api-version: 1.21

commands:
  roozie:
    description: Basiscommand voor RooziePlugin
    usage: /roozie.reload
    permission: roozie.admin

  rolemenu:
    description: Open het menu
    usage: /rolemenu

  help:
    description: Toon help informatie
    usage: /help

  resetrol:
    description: Reset jouw rol en kies opnieuw
    usage: /resetrol

  roleupgrade:
    description: Upgrade je rol als Team-owner
    usage: /upgraderole

  team:
    description: team beheer (create/invite/accept/leave/disband/info)
    usage: /team <subcommand>

  togglename:
    description: Zet naamzichtbaarheid aan of uit
    usage: /togglename
    permission: roozie.name.toggle

  # Emote commands
  emote:
    description: Gebruik een aangepaste emote
    usage: /emote <naam>

  wave:
    description: Doe de emote 'wave'
  cry:
    description: Doe de emote 'cry'
  sit:
    description: Doe de emote 'sit'
  kiss:
    description: Doe de emote 'kiss'
  holdhand:
    description: Doe de emote 'holdhand'
  blush:
    description: Doe de emote 'blush'
  love:
    description: Doe de emote 'love'
  pain:
    description: Doe de emote 'pain'
  angry:
    description: Doe de emote 'angry'
  shocked:
    description: Doe de emote 'shocked'
  ashamed:
    description: Doe de emote 'ashamed'
  laugh:
    description: Doe de emote 'laugh'
  lie_down:
    description: Doe de emote 'lie_down'
  scared:
    description: Doe de emote 'scared'
  jealous:
    description: Doe de emote 'jealous'
  shy:
    description: Doe de emote 'shy'
  surprised:
    description: Doe de emote 'surprised'
  proud:
    description: Doe de emote 'proud'
  serious:
    description: Doe de emote 'serious'
  calm:
    description: Doe de emote 'calm'
  dream:
    description: Doe de emote 'dream'
  sleep:
    description: Doe de emote 'sleep'
  kneel:
    description: Doe de emote 'kneel'
  hug:
    description: Doe de emote 'hug'
  push:
    description: Doe de emote 'push'
  grab:
    description: Doe de emote 'grab'
  fall:
    description: Doe de emote 'fall'

permissions:
  roozie.admin:
    default: op
  roozie.rol.herkiezen:
    default: op
