name: RooziesPlugin
version: 0.1-1.21.5
main: com.roozie.roozieplugin.RooziesPlugin
description: A custom plugin for roleplay
author: Djskinproductions
api-version: 1.21

commands:
  help:
    description: help
    usage: /help
  resetrol:
    description: Reset jou rol en kies opnieuw
    usage: /rolreset
  wave:
  cry:
  sit:
  kiss:
  holdhand:

permissions:
  roozie.help:
    description: Roozie's help
    default: true
  roozie.rol.ultima:
    description: Mag Ultima Weerwolf kiezen
    default: op
  roozie.rol.herkiezen:
    description: Mag opnieuw een rol kiezen
    default: op
  roozie.rol.reset:
    description: Reset je rol
    default: op
