name: RooziesPlugin
version: 0.1-1.21.5
main: com.roozie.roozieplugin.RooziesPlugin
description: A custom plugin for roleplay
author: Djskinproductions

commands:
  help:
    description: Rooziesplugin Commands
    permission: roozie.help
    usage: /help
  resetrol:
    description: Reset jou rol en kies opnieuw
    permission: roozie.rol.herkiezen
    usage: /resetrol
api-version: 1.21

permissions:
  roozie.rol.ultima:
    description: Mag Ultima Weerwolf kiezen
    default: op
  roozie.rol.herkiezen:
    description: Mag opnieuw een rol kiezen
    default: false
